export const WEBSOCKET_CONNECT = 'WEBSOCKET:CONNECT';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET:DISCONNECT';
export const WEBSOCKET_SEND = 'WEBSOCKET:SEND';

// Action types dispatched by the WebSocket implementation
export const WEBSOCKET_CONNECTING = 'WEBSOCKET:CONNECTING';
export const WEBSOCKET_OPEN = 'WEBSOCKET:OPEN';
export const WEBSOCKET_CLOSED = 'WEBSOCKET:CLOSED';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET:MESSAGE';

export const WEBSOCKET_EVENTS_LIST =  'WEBSOCKET:EVENTS_LIST';
export const WEBSOCKET_SENDING = 'WEBSOCKET:SENDING';
export const WEBSOCKET_EVENT_DECISION = 'WEBSOCKET:EVENT_DECISION';

const IP_ADDRESS = 'localhost';//'51.15.66.253';
const PORT = '3000';
export const URL = `http://${IP_ADDRESS}:${PORT}`; 
export const WS_URL = `ws://${IP_ADDRESS}:${PORT}`;
