# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 


target 'OAuthLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
    pod 'YandexMoneySDKObjc', '~> 2.1.1'
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

  # Pods for YandexWrapper

  # target 'YandexWrapper-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'YandexWrapperTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'YandexWrapper-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for YandexWrapper-tvOS

#   target 'YandexWrapper-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
